spring:
  datasource:
    url: jdbc:postgresql://localhost:5430/library_social_network_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: ${EMAIL_HOSTNAME}
    port: 1025
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls: true
        connectiontimeout: 5000
        timeout: 4000
        writeTimeout: 4000

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000 # 1 day
  refresh-token:
    expiration: 604800000 # 1 week

mailing:
  frontend:
    activation-url: http://localhost:5173/activate-account

file:
  uploads:
    photos-output-path: ./uploads

server:
  port: 8088
